import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { randomUUID, scryptSync } from 'node:crypto'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { test } from 'node:test'
import { createDatabase } from '../src/database.js'
import { createAuthRepository, createCustomerRepository } from '../src/customer.js'
import { createAssetRepository } from '../src/asset.js'
import { createAdminAccountRepository } from '../src/admin-accounts.js'
import { hashPassword } from '../src/auth.js'
import { adminDataQuery, createAdminDataRepository } from '../src/admin-data.js'
import { adminListQuery } from '../src/admin-pagination.js'
import { createAdminImageRepository, imageOrigin } from '../src/admin-images.js'
import { createReceivingRepository, receivingInput, receivingQuery, receivingTerms } from '../src/receiving.js'
import { createInspectionRepository, inspectionWrite, receiveInput } from '../src/inspection.js'
import { createLocationRepository } from '../src/location.js'

test('customer migration and repositories on isolated MySQL', { skip: process.env.RUN_CUSTOMER_SCHEMA_TEST !== '1' }, async (context) => {
  const container = `mrs-customer-test-${randomUUID()}`
  const docker = (args: string[], input?: string) => execFileSync('docker', args, { input, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 180_000 }).trim()
  context.after(() => docker(['rm', '--force', '--volumes', container]))
  docker(['run', '--detach', '--name', container, '--publish', '127.0.0.1::3306', '--env', 'MYSQL_ALLOW_EMPTY_PASSWORD=yes', '--env', 'MYSQL_ROOT_HOST=%', '--env', 'MYSQL_DATABASE=customer_test', 'mysql:8.4.11', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci'])
  docker(['exec', container, 'mysqladmin', '--protocol=TCP', '--host=127.0.0.1', '--wait=120', '--connect-timeout=1', 'ping', '--silent'])
  const sql = (statement: string) => docker(['exec', '-i', container, 'mysql', '--default-character-set=utf8mb4', '--database=customer_test', '--batch', '--skip-column-names'], statement)
  const migrations = new URL('../prisma/migrations/', import.meta.url)
  for (const directory of readdirSync(migrations, { withFileTypes: true }).filter((entry) => entry.isDirectory()).sort((left, right) => left.name.localeCompare(right.name))) {
    const migration = new URL(`${directory.name}/migration.sql`, migrations)
    if (directory.name === '20260930000000_add_customers') sql(`
      INSERT INTO users (id,email,passwordHash,companyName,managerName,managerPhone,customerId,status,updatedAt) VALUES ('legacy-user','legacy@example.test','unused','Legacy','Manager','010','LEGACY-CUS','ACTIVE',NOW(3));
      INSERT INTO material_categories (id,name) VALUES ('880000','Legacy category');
      INSERT INTO master_items (id,name,categoryId,specification,brand,unit,note,updatedAt) VALUES ('880001','Legacy item','880000','Spec','','EA','',NOW(3));
      INSERT INTO assets (id,itemId,receivingId,customerId,categoryId,name,specification,brand,grade,quantity,unit,appraisal,storageStatus,saleStatus,updatedAt) VALUES ('260929-0001','880001','LEGACY-RCV','LEGACY-ASSET-OWNER','880000','Legacy asset','Spec','','A',2.500,'EA',12345,'보관중','판매대기',NOW(3));
    `)
    if (directory.name === '20261002000000_first_inspection_locations') sql("UPDATE assets SET locationId='LEGACY-LOC' WHERE id='260929-0001'")
    if (existsSync(migration)) sql(readFileSync(migration, 'utf8'))
  }
  assert.equal(sql("SELECT CONCAT(id, ':', status, ':', businessNumber IS NULL) FROM customers WHERE id='LEGACY-CUS'"), 'LEGACY-CUS:PENDING:1')
  assert.equal(sql("SELECT status FROM users WHERE id='legacy-user'"), 'PENDING')
  assert.equal(sql("SELECT CONCAT(id, ':', status) FROM customers WHERE id='LEGACY-ASSET-OWNER'"), 'LEGACY-ASSET-OWNER:PENDING')
  assert.equal(sql("SELECT CONCAT(COUNT(*), ':', SUM(quantity), ':', SUM(appraisal)) FROM assets WHERE customerId='LEGACY-ASSET-OWNER'"), '1:2.500:12345')
  assert.equal(sql("SELECT CONCAT(id, ':', enabled) FROM locations WHERE id='LEGACY-LOC'"), 'LEGACY-LOC:0')
  assert.equal(sql("SELECT locationId FROM assets WHERE id='260929-0001'"), 'LEGACY-LOC')
  assert.throws(() => sql("DELETE FROM locations WHERE id='LEGACY-LOC'"), /Command failed/)
  assert.throws(() => sql("UPDATE users SET customerId='MISSING' WHERE id='legacy-user'"), /Command failed/)
  assert.throws(() => sql("DELETE FROM customers WHERE id='LEGACY-CUS'"), /Command failed/)
  const port = Number(docker(['port', container, '3306/tcp']).split(':').at(-1))
  const database = createDatabase({ host: '127.0.0.1', port, name: 'customer_test', user: 'root', password: '', poolMax: 5, timeoutMs: 5000 })
  context.after(() => database.close())
  const client = database.client
  const customers = createCustomerRepository(client)
  const auth = createAuthRepository(client)
  const admin = await client.user.create({ data: { email: 'admin@example.test', passwordHash: 'unused', companyName: 'MRS', managerName: 'Admin', managerPhone: '010', role: 'ADMIN', adminRole: 'SYSTEM_ADMIN', status: 'ACTIVE' } })
  await context.test('administrator accounts hash passwords, isolate customers, audit and preserve the last system administrator', async () => {
    const verifyPassword = (password: string, encoded: string) => {
      const [algorithm, salt, stored] = encoded.split('$')
      return algorithm === 'scrypt' && !!salt && !!stored && scryptSync(password, Buffer.from(salt, 'base64url'), 64).equals(Buffer.from(stored, 'base64url'))
    }
    const accounts = createAdminAccountRepository(client)
    const fields = { loginId: 'sales.test', password: 'password123', name: 'Sales staff', phone: '010', adminRole: 'SALES' as const, status: 'ACTIVE' as const, reason: 'MRS verified staff' }
    const account = await accounts.create(fields, admin.id)
    assert.equal('passwordHash' in account, false)
    assert.equal((await accounts.list()).some((entry) => 'passwordHash' in entry), false)
    assert.equal((await client.user.findUniqueOrThrow({ where: { id: account.id } })).role, 'ADMIN')
    assert.equal(await verifyPassword('password123', (await client.user.findUniqueOrThrow({ where: { id: account.id } })).passwordHash), true)
    const beforeAudit = await client.customerChange.count()
    await assert.rejects(accounts.create(fields, admin.id), /상태/)
    assert.equal(await client.customerChange.count(), beforeAudit)
    await assert.rejects(accounts.create({ ...fields, loginId: 'denied.test' }, account.id), /시스템 관리자/)
    await assert.rejects(accounts.update('legacy-user', { ...fields, version: 0 }, admin.id), /관리자 계정/)
    await assert.rejects(accounts.update(admin.id, { ...fields, version: 0 }, admin.id), /마지막 활성/)
    const changed = await accounts.update(account.id, { ...fields, adminRole: 'LOGISTICS', version: 0, password: 'changed123' }, admin.id)
    assert.equal(changed.adminRole, 'LOGISTICS')
    assert.equal(changed.sessionVersion, 1)
    assert.equal(await verifyPassword('changed123', (await client.user.findUniqueOrThrow({ where: { id: account.id } })).passwordHash), true)
    await assert.rejects(accounts.update(account.id, { ...fields, version: 0 }, admin.id), /계정 상태/)
    const suspended = await accounts.update(account.id, { ...fields, status: 'SUSPENDED', version: 1 }, admin.id)
    assert.equal(suspended.status, 'SUSPENDED')
    const audit = await client.customerChange.findMany({ where: { targetUserId: account.id }, orderBy: { createdAt: 'asc' } })
    assert.equal(audit.length, 3)
    assert.equal(JSON.stringify(audit).includes('changed123'), false)
    assert.equal(JSON.stringify(audit).includes('passwordHash'), false)
    await client.user.create({ data: { email: 'concurrent-system.test', passwordHash: await hashPassword('password123'), companyName: 'MRS', managerName: 'System 2', managerPhone: '', role: 'ADMIN', adminRole: 'SYSTEM_ADMIN', status: 'ACTIVE' } })
    const systems = (await accounts.list()).filter((entry) => entry.adminRole === 'SYSTEM_ADMIN' && entry.status === 'ACTIVE')
    const results = await Promise.allSettled(systems.map((entry) => accounts.update(entry.id, { ...fields, status: 'SUSPENDED', version: entry.sessionVersion }, entry.id)))
    assert.equal(results.filter((result) => result.status === 'fulfilled').length, 1)
    assert.equal(await client.user.count({ where: { role: 'ADMIN', adminRole: 'SYSTEM_ADMIN', status: 'ACTIVE' } }), 1)
    await client.user.update({ where: { id: admin.id }, data: { status: 'ACTIVE', adminRole: 'SYSTEM_ADMIN' } })
  })
  const fields = { name: 'Company A', businessNumber: '2208162517', representativeName: 'Owner', phone: '0212345678', address: 'Seoul' }
  const company = await customers.create(fields, 'Verified company', admin.id)
  await context.test('duplicate companies cannot be created and failed changes leave no audit', async () => {
    const before = await client.customerChange.count()
    await assert.rejects(customers.create(fields, 'Duplicate', admin.id), /상태/)
    assert.equal(await client.customerChange.count(), before)
  })
  const user = await auth.createRegistration({ email: 'member@example.test', passwordHash: 'unused', customerType: 'existing', customerId: company.id, managerName: 'Manager', managerPhone: '010' })
  await context.test('selecting a company grants no access; only MRS approval activates membership', async () => {
    assert.equal(user.status, 'PENDING')
    assert.equal(user.customerRole, 'VIEWER')
    const approved = await auth.approveMember(user.id, new Date(), { action: 'approve', reason: 'Confirmed through company contact', version: 0, customerRole: 'MANAGER' }, admin.id)
    assert.equal(approved?.status, 'ACTIVE')
    assert.equal(approved?.customerRole, 'MANAGER')
    await assert.rejects(auth.approveMember(user.id, new Date(), { action: 'approve', reason: 'Duplicate', version: 0, customerRole: 'MANAGER' }, admin.id))
  })
  await context.test('company suspension preserves individual suspension and rejects stale changes', async () => {
    await auth.changeMember!(user.id, { action: 'suspend', reason: 'Employee left', version: 1, customerRole: 'VIEWER' }, admin.id)
    const suspended = await customers.changeStatus(company.id, 'SUSPENDED', { version: 0, reason: 'Company suspended' }, admin.id)
    await assert.rejects(customers.update(company.id, fields, { version: 0, reason: 'Stale edit' }, admin.id))
    await customers.changeStatus(company.id, 'ACTIVE', { version: suspended.version, reason: 'Company restored' }, admin.id)
    assert.equal((await auth.findById(user.id))?.status, 'SUSPENDED')
    assert.equal((await auth.findById(user.id))?.customer?.accessVersion, 2)
  })
  await context.test('new applications do not reserve business numbers or silently approve users', async () => {
    const applicant = await auth.createRegistration({ email: 'new@example.test', passwordHash: 'unused', customerType: 'new', customer: fields, managerName: 'New member', managerPhone: '010' })
    const application = (await customers.applications()).find((entry) => entry.userId === applicant.id)!
    assert.equal(applicant.customerId, null)
    await assert.rejects(customers.review(application.id, { action: 'approve', version: 0, reason: 'Missing duplicate confirmation' }, admin.id))
    await customers.review(application.id, { action: 'approve', customerId: company.id, version: 0, reason: 'Existing company verified' }, admin.id)
    assert.equal((await auth.findById(applicant.id))?.status, 'PENDING')
    assert.equal((await auth.findById(applicant.id))?.customerId, company.id)
  })
  await context.test('shared rate limits reject excessive requests', async () => {
    await customers.throttle('test', 'identity', 1)
    await assert.rejects(customers.throttle('test', 'identity', 1), /요청이 많습니다/)
  })
  await context.test('receiving requests persist optional photos, consent and audit and isolate customer ownership', async () => {
    const member = await client.user.create({ data: { email: 'receiving-member@example.test', passwordHash: 'unused', companyName: company.name, managerName: '신청 담당자', managerPhone: '01012345678', role: 'CUSTOMER', status: 'ACTIVE', customerRole: 'VIEWER', customerId: company.id } })
    const current = (await auth.findById(member.id))!
    const repository = createReceivingRepository(client)
    const input = receivingInput.parse({ siteName: '입고 검증 현장', managerName: '신청 담당자', managerPhone: '01012345678', volume: 'UNDER_ONE_TON', note: '오전 수거 희망', disposalTerms: 'true' })
    const first = await repository.create(current, input, [])
    assert.equal(first.status, 'REQUESTED')
    assert.equal(first.channel, 'PORTAL')
    assert.equal(first.customerId, company.id)
    assert.equal(first.siteId, null)
    assert.equal(first.images.length, 0)
    assert.equal(first.termsVersion, receivingTerms.version)
    assert.equal(first.termsText, receivingTerms.text)
    assert.equal((await client.receivingChange.findFirstOrThrow({ where: { receivingId: first.id } })).actorUserId, member.id)
    const images = Array.from({ length: 5 }, (_, index) => ({ id: randomUUID(), name: `현장-${index}.webp`, url: `${imageOrigin}/receivings/${company.id}/${member.id}/${randomUUID()}.webp` }))
    const second = await repository.create(current, input, images)
    assert.deepEqual(second.images.map(({ id, name, url }) => ({ id, name, url })), images)
    const page = await repository.list(company.id, receivingQuery.parse({ size: 1, page: 2, status: 'REQUESTED', q: '입고 검증' }))
    assert.equal(page.totalElements, 2)
    assert.equal(page.records.length, 1)
    assert.equal(await repository.detail('OTHER-COMPANY', first.id), null)
    assert.equal((await repository.detail(company.id, second.id))?.images.length, 5)
    const adminData = createAdminDataRepository(client)
    const detail = (await adminData.load(adminDataQuery.parse({ scope: 'receivings', id: second.id }))).receivings[0]!
    assert.equal(detail.siteName, input.siteName)
    assert.equal(detail.managerPhone, input.managerPhone)
    assert.equal(detail.images?.length, 5)
    assert.equal(detail.termsText, receivingTerms.text)
    const list = await adminData.load(adminDataQuery.parse({ scope: 'receivings', customer: company.id }))
    assert.equal(list.receivings.every((entry) => !('images' in entry)), true)
    const reviewer = (await auth.findById(admin.id))!
    const approved = await repository.review(first.id, { action: 'approve', reason: '수거 조건 확인' }, reviewer)
    assert.equal(approved.status, 'APPROVED')
    assert.equal(approved.scheduledAt, null)
    assert.equal(approved.receivedAt, null)
    assert.equal(approved.history.length, 2)
    assert.equal(approved.history[1]!.actorUserId, admin.id)
    assert.deepEqual(approved.history[1]!.changes, { status: { before: 'REQUESTED', after: 'APPROVED' } })
    const rejected = await repository.review(second.id, { action: 'reject', reason: '수거 조건 협의 불가' }, reviewer)
    assert.equal(rejected.status, 'REJECTED')
    assert.equal(rejected.images.length, 5)
    assert.equal((await adminData.load(adminDataQuery.parse({ scope: 'receivings', id: second.id }))).receivings[0]!.decision?.reason, '수거 조건 협의 불가')
    assert.equal((await repository.detail(company.id, second.id))?.history[1]!.reason, '수거 조건 협의 불가')
    for (const record of [first, second]) await assert.rejects(repository.review(record.id, { action: 'approve', reason: '재처리' }, reviewer), /이미 처리/)
    const contested = await repository.create(current, input, [])
    await assert.rejects(repository.review(contested.id, { action: 'approve', reason: '비관리자' }, current), /관리자 권한/)
    await assert.rejects(repository.review(contested.id, { action: 'approve', reason: '폐기된 세션' }, { ...reviewer, sessionVersion: reviewer.sessionVersion! + 1 }), /관리자 권한/)
    await assert.rejects(repository.review('MISSING', { action: 'approve', reason: '없는 신청' }, reviewer), /찾을 수/)
    const decisions = await Promise.allSettled([
      repository.review(contested.id, { action: 'approve', reason: '관리자 승인' }, reviewer),
      repository.review(contested.id, { action: 'reject', reason: '관리자 반려' }, reviewer),
    ])
    assert.equal(decisions.filter((result) => result.status === 'fulfilled').length, 1)
    const conflict = decisions.find((result) => result.status === 'rejected') as PromiseRejectedResult
    assert.equal(conflict.reason.status, 409)
    assert.equal(await client.receivingChange.count({ where: { receivingId: contested.id } }), 2)
    const rollback = await repository.create(current, input, [])
    sql("CREATE TRIGGER test_receiving_review_failure BEFORE INSERT ON receiving_changes FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'test audit failure'")
    try { await assert.rejects(repository.review(rollback.id, { action: 'approve', reason: '이력 실패' }, reviewer)) }
    finally { sql('DROP TRIGGER test_receiving_review_failure') }
    assert.equal((await repository.detail(company.id, rollback.id))?.status, 'REQUESTED')
    assert.equal(await client.receivingChange.count({ where: { receivingId: rollback.id } }), 1)
    for (const status of ['RECEIVED', 'CANCELLED'] as const) {
      await client.receiving.update({ where: { id: rollback.id }, data: { status, receivedAt: status === 'RECEIVED' ? new Date() : null } })
      await assert.rejects(repository.review(rollback.id, { action: 'reject', reason: '처리 불가' }, reviewer), /이미 처리/)
    }
    const before = await client.receiving.count()
    await assert.rejects(repository.create(current, input, [images[0]!, images[0]!]))
    assert.equal(await client.receiving.count(), before)
    await client.user.update({ where: { id: member.id }, data: { status: 'SUSPENDED' } })
    await assert.rejects(repository.create(current, input, []), /소속 확인/)
    assert.equal(await client.receiving.count(), before)
  })
  await context.test('first inspection drafts, optional-item assets, amendments and material-only consent persist atomically', async () => {
    await client.materialCategory.createMany({ data: [{ id: '770000', name: '검수 분류' }, { id: '770100', name: '검수 중분류', parentId: '770000' }, { id: '770101', name: '검수 소분류', parentId: '770100' }] })
    const locationRepository = createLocationRepository(client)
    const location = await locationRepository.save(null, { name: '검수 창고', zone: 'A', enabled: true, reason: '위치 등록' }, (await auth.findById(admin.id))!)
    const inspectionCompany = await client.customer.create({ data: { ...fields, id: 'CUS-INSPECTION', name: '검수 고객사', businessNumber: '1234567890', status: 'ACTIVE' } })
    const member = await client.user.create({ data: { email: 'inspection@example.test', passwordHash: 'unused', companyName: inspectionCompany.name, managerName: '검수 담당', managerPhone: '010', role: 'CUSTOMER', customerRole: 'MANAGER', customerId: inspectionCompany.id, status: 'ACTIVE' } })
    const manager = (await auth.findById(member.id))!, reviewer = (await auth.findById(admin.id))!
    const receivings = createReceivingRepository(client), repository = createInspectionRepository(client)
    const receiving = await receivings.create(manager, receivingInput.parse({ siteName: '검수 현장', managerName: '담당', managerPhone: '010', volume: 'UNDER_ONE_TON', disposalTerms: 'true' }), [])
    await assert.rejects(repository.receive(receiving.id, receiveInput.parse({ receivedAt: '2026-09-28T12:00:00+09:00', reason: '실제 입고' }), reviewer))
    await receivings.review(receiving.id, { action: 'approve', reason: '승인' }, reviewer)
    const initial = await repository.receive(receiving.id, receiveInput.parse({ receivedAt: '2026-09-28T12:00:00+09:00', reason: '실제 입고' }), reviewer)
    await assert.rejects(repository.receive(receiving.id, receiveInput.parse({ receivedAt: '2026-09-28T12:00:00+09:00', reason: '중복' }), reviewer))
    const row = { id: randomUUID(), itemId: '', name: '품목 없는 자산', specification: '', brand: '', categoryId: '', unit: 'EA', grade: 'A', received: '10', usable: '8', disposal: '2', reason: '파손', locationId: location.id, photos: [] }
    const unused = { ...row, id: randomUUID(), name: '전량 폐기 행', grade: 'F', received: '5', usable: '0', disposal: '5', locationId: '' }
    const draft = await repository.draft(initial.id, inspectionWrite.parse({ version: 0, rows: [{ ...row, grade: '', received: '' }], reason: '작성 중' }), reviewer)
    await assert.rejects(repository.detail(initial.id, inspectionCompany.id))
    const before = await client.asset.count()
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [unused], reason: '전량 폐기' }), reviewer, false))
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [{ ...row, disposal: '3' }], reason: '수량 오류' }), reviewer, false))
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [{ ...row, categoryId: '770100' }], reason: '잘못된 분류' }), reviewer, false), /카테고리/)
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [{ ...row, itemId: '028818' }], reason: '미등록 품목' }), reviewer, false), /품목코드 028818는 등록되지 않았습니다/)
    await client.masterItem.create({ data: { id: '778818', name: '검수 단위 검증', specification: '', unit: 'M', enabled: true, note: '' } })
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [{ ...row, itemId: '778818' }], reason: '단위 불일치' }), reviewer, false), /기준 단위는 M.*입력 단위 EA/)
    await client.masterItem.update({ where: { id: '778818' }, data: { enabled: false } })
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [{ ...row, itemId: '778818' }], reason: '미사용 품목' }), reviewer, false), /미사용 상태/)
    assert.equal(await client.asset.count(), before)
    sql("CREATE TRIGGER test_inspection_audit_failure BEFORE INSERT ON receiving_changes FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='audit failure'")
    try { await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [row, unused], reason: '확정' }), reviewer, false)) }
    finally { sql('DROP TRIGGER test_inspection_audit_failure') }
    assert.equal(await client.asset.count(), before)
    const confirmed = await repository.save(initial.id, inspectionWrite.parse({ version: draft.version, rows: [row, unused], reason: '확정' }), reviewer, false)
    assert.equal(confirmed.assets.length, 1)
    assert.match(confirmed.assets[0]!.id, /^260928-\d{4}$/)
    const asset = await client.asset.findUniqueOrThrow({ where: { id: confirmed.assets[0]!.id } })
    assert.equal(asset.itemId, null); assert.equal(asset.quantity.toString(), '8'); assert.equal(asset.storageStatus, 'STORED'); assert.equal(asset.appraisal, null)
    assert.equal(asset.categoryId, null); assert.equal(asset.specification, '')
    const savedRow = await client.inspectionItem.findUniqueOrThrow({ where: { id: row.id } })
    assert.equal(savedRow.categoryId, null); assert.equal(savedRow.specification, '')
    assert.equal((await client.disposalItem.count({ where: { inspectionId: initial.id } })), 2)
    assert.equal(confirmed.editable, true)
    const amended = await repository.save(initial.id, inspectionWrite.parse({ version: confirmed.version, rows: [{ ...row, usable: '7', disposal: '3' }, unused], reason: '검수 수량 정정' }), reviewer, true)
    assert.equal(amended.assets[0]!.id, asset.id)
    assert.equal(amended.editable, true)
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: amended.version, rows: [row], reason: '행 삭제' }), reviewer, true))
    await client.user.update({ where: { id: member.id }, data: { customerRole: 'VIEWER' } })
    await assert.rejects(repository.customerAction(initial.id, amended.version, manager, false))
    await client.user.update({ where: { id: member.id }, data: { customerRole: 'MANAGER' } })
    await repository.customerAction(initial.id, amended.version, manager, false)
    const current = await repository.detail(initial.id, inspectionCompany.id)
    assert.equal(current.status, 'COMPLETED')
    await assert.rejects(repository.save(initial.id, inspectionWrite.parse({ version: current.version, rows: [row, unused], reason: '확인 후 수정' }), reviewer, true))
    const agreed = await repository.customerAction(initial.id, current.version, manager, true)
    assert.ok(agreed.consentedAt)
    const disposal = await client.disposal.findUniqueOrThrow({ where: { inspectionId: initial.id } })
    assert.equal(disposal.costStatus, 'UNESTIMATED'); assert.equal(disposal.amount, null); assert.equal(disposal.status, 'UNPROCESSED')
    await assert.rejects(repository.detail(initial.id, 'OTHER'))
    await assert.rejects(repository.customerAction(initial.id, agreed.version, (await auth.findById(user.id))!, true))
    const actual = await createAssetRepository(client).detail!(inspectionCompany.id, asset.id)
    assert.equal(actual?.itemId, null)
    assert.equal(actual?.category, null)
    const assetPage = await createAssetRepository(client).list(inspectionCompany.id, { page: 1, size: 20, sort: 'updatedDesc' }, new Date())
    assert.equal(assetPage.records[0]!.category, null)
    await client.user.update({ where: { id: member.id }, data: { customerRole: 'VIEWER' } })
    await assert.rejects(repository.customerAction(initial.id, agreed.version, manager, true))
    const disabled = await locationRepository.save(location.id, { name: location.name, zone: location.zone, enabled: false, version: location.version, reason: '사용중지' }, reviewer)
    assert.equal(disabled.enabled, false)
    assert.equal((await locationRepository.list({ page: 1, size: 20, q: location.name })).locations[0]!.assetCount, 1)
    await assert.rejects(client.location.delete({ where: { id: location.id } }))
  })
  await context.test('inspection concurrency, downstream-change guards and maximum XLSX row count preserve assets', async () => {
    const member = await client.user.findUniqueOrThrow({ where: { email: 'inspection@example.test' } })
    await client.user.update({ where: { id: member.id }, data: { customerRole: 'MANAGER' } })
    const manager = (await auth.findById(member.id))!, reviewer = (await auth.findById(admin.id))!
    const locations = createLocationRepository(client)
    const location = await locations.save(null, { name: '대량 검수 위치', zone: 'B', enabled: true, reason: '검증' }, reviewer)
    const receivings = createReceivingRepository(client), inspections = createInspectionRepository(client)
    const create = async (date: string) => {
      const receiving = await receivings.create(manager, receivingInput.parse({ siteName: '대량 검수 현장', managerName: '담당', managerPhone: '010', volume: 'UNDER_ONE_TON', disposalTerms: 'true' }), [])
      await receivings.review(receiving.id, { action: 'approve', reason: '승인' }, reviewer)
      return inspections.receive(receiving.id, receiveInput.parse({ receivedAt: `${date}T23:30:00+09:00`, reason: '입고' }), reviewer)
    }
    const row = { id: randomUUID(), itemId: '', name: '검증 자산', specification: '규격', brand: '', categoryId: '770101', unit: 'M', grade: 'A', received: '1.125', usable: '1.125', disposal: '0', reason: '', locationId: location.id, photos: [] }
    const initial = await create('2026-09-26')
    const input = inspectionWrite.parse({ version: 0, rows: [row], reason: '확정' })
    const concurrent = await Promise.allSettled([inspections.save(initial.id, input, reviewer, false), inspections.save(initial.id, input, reviewer, false)])
    assert.equal(concurrent.filter((result) => result.status === 'fulfilled').length, 1)
    const confirmed = await inspections.detail(initial.id)
    assert.equal(confirmed.assets.length, 1)
    assert.equal(await client.disposal.count({ where: { inspectionId: initial.id } }), 0)
    await client.asset.update({ where: { id: confirmed.assets[0]!.id }, data: { name: '후속 자산 수정' } })
    assert.equal((await inspections.detail(initial.id)).editable, false)
    await assert.rejects(inspections.save(initial.id, inspectionWrite.parse({ ...input, version: confirmed.version }), reviewer, true))
    const second = await create('2026-09-26')
    const next = await inspections.save(second.id, inspectionWrite.parse({ ...input, rows: [{ ...row, id: randomUUID() }] }), reviewer, false)
    assert.notEqual(next.assets[0]!.id, confirmed.assets[0]!.id)
    const disposalReport = await create('2026-09-26')
    const disposalInput = inspectionWrite.parse({ version: 0, rows: [{ ...row, id: randomUUID(), received: '2.125', disposal: '1', reason: '파손' }], reason: '폐기 대상 확정' })
    const disposalConfirmed = await inspections.save(disposalReport.id, disposalInput, reviewer, false)
    await client.disposalCostLine.create({ data: { inspectionId: disposalReport.id, label: '후속 비용 입력', amount: '100' } })
    assert.equal((await inspections.detail(disposalReport.id)).editable, false)
    await assert.rejects(inspections.save(disposalReport.id, { ...disposalInput, version: disposalConfirmed.version }, reviewer, true))
    const third = await create('2026-09-25')
    const disabled = await locations.save(location.id, { name: location.name, zone: location.zone, enabled: false, version: location.version, reason: '미사용 검증' }, reviewer)
    assert.equal((await locations.list({ page: 1, size: 100, q: '', enabled: 'true' })).locations.some((entry) => entry.id === location.id), false)
    assert.equal((await locations.list({ page: 1, size: 100, q: '', enabled: 'false' })).locations.some((entry) => entry.id === location.id), true)
    await assert.rejects(inspections.save(third.id, input, reviewer, false), /로케이션/)
    await locations.save(location.id, { name: location.name, zone: location.zone, enabled: true, version: disabled.version, reason: '복구' }, reviewer)
    const bulk = await inspections.save(third.id, inspectionWrite.parse({ version: 0, rows: Array.from({ length: 1000 }, () => ({ ...row, id: randomUUID() })), reason: '1000행 확정' }), reviewer, false)
    assert.equal(bulk.assets.length, 1000)
    assert.equal(new Set(bulk.assets.map((asset) => asset.id)).size, 1000)
    assert.equal(bulk.assets.at(-1)!.id, '260925-1000')
    assert.equal(await client.disposal.count({ where: { inspectionId: third.id } }), 0)
  })
  await context.test('real asset queries isolate detail, images, pagination and full-company totals', async () => {
    const other = await client.customer.create({ data: { id: 'OTHER', name: 'Other' } })
    await client.materialCategory.create({ data: { id: '990000', name: 'Root' } })
    await client.materialCategory.create({ data: { id: '990100', name: 'Middle', parentId: '990000' } })
    await client.materialCategory.create({ data: { id: '990101', name: 'Leaf', parentId: '990100' } })
    await client.masterItem.create({ data: { id: '990001', categoryId: '990101', name: 'Material', specification: 'Spec', unit: 'EA', note: '' } })
    const record = { itemId: '990001', receivingId: 'LEGACY-RECEIVING', categoryId: '990101', name: 'Asset', specification: 'Spec', grade: 'A' as const, quantity: '1.250', unit: 'EA' as const, storageStatus: 'STORED' as const, saleStatus: 'PENDING' as const }
    await client.asset.createMany({ data: Array.from({ length: 101 }, (_, index) => ({ ...record, id: `260930-${String(index + 1).padStart(4, '0')}`, customerId: company.id, appraisal: index === 0 ? null : index === 1 ? '0' : '10' })) })
    await client.asset.create({ data: { ...record, id: '260930-9998', customerId: other.id, appraisal: '999999' } })
    await client.asset.create({ data: { ...record, id: '260930-9999', customerId: company.id, appraisal: '777777', quantity: '0', storageStatus: 'RELEASED' } })
    await client.assetImage.createMany({ data: [{ id: 'image-private', assetId: '260930-0001', name: 'Private image', url: 'https://private.example.test/secret.jpg', sortOrder: 0 }, { id: 'image-safe', assetId: '260930-0001', name: 'Stored image', url: 'data:image/png;base64,aGVsbG8=', sortOrder: 1 }] })
    const assets = createAssetRepository(client)
    const page = await assets.list(company.id, { page: 2, size: 100, sort: 'nameAsc', storageStatus: 'STORED' }, new Date())
    assert.equal(page.totalElements, 101)
    assert.equal(page.records.length, 1)
    const totals = await assets.summary!(company.id)
    assert.equal(totals.total, 101)
    assert.equal(totals.appraisalValue, '990')
    assert.equal(totals.unappraised, 1)
    assert.deepEqual(totals.quantities, [{ unit: 'EA', quantity: '126.25' }])
    assert.equal(await assets.detail!(other.id, '260930-0001'), null)
    const detail = await assets.detail!(company.id, '260930-0001')
    assert.deepEqual(detail?.images.map((image) => image.id), ['image-safe'])
    assert.equal(detail?.appraisalValue, null)
    assert.equal((await assets.detail!(company.id, '260930-0002'))?.appraisalValue, '0')
    const adminData = createAdminDataRepository(client)
    const first = await adminData.load(adminDataQuery.parse({ scope: 'assets', customer: company.id, page: 1, rows: 10 }))
    const second = await adminData.load(adminDataQuery.parse({ scope: 'assets', customer: company.id, page: 2, rows: 10 }))
    assert.equal(first.assets.length, 10)
    assert.equal(second.assets.length, 10)
    assert.equal(first.pagination.total, 102)
    assert.equal(second.assets.some((entry) => first.assets.some((previous) => previous.id === entry.id)), false)
    assert.equal(first.items.length, 0)
    assert.equal(first.assets.every((entry) => entry.history.length === 0), true)
    const selected = await adminData.load(adminDataQuery.parse({ scope: 'assets', id: second.assets[0]!.id, page: 50 }))
    assert.equal(selected.assets[0]?.id, second.assets[0]!.id)
    const companyPage = adminListQuery.parse({ rows: 1, page: 2 })
    assert.equal((await customers.list(companyPage)).length, 1)
    assert.ok(await customers.count(companyPage) >= 2)
    await client.receiving.create({ data: { id: 'MISMATCH', customerId: other.id, siteName: 'Other site', managerName: 'Manager', managerPhone: '010', channel: 'ADMIN', volume: 'OTHER', termsAgreedAt: new Date(), termsVersion: 'v1', termsText: 'Test' } })
    await client.asset.update({ where: { id: '260930-0001' }, data: { receivingId: 'MISMATCH' } })
    await assert.rejects(assets.summary!(company.id), /귀속 확인/)
    await assert.rejects(assets.detail!(other.id, '260930-9998'), /귀속 확인/)
  })
  await context.test('S3 image references persist for items and assets, audit atomically and reject stale replacement', async () => {
    const repository = createAdminImageRepository(client)
    const itemImage = { id: randomUUID(), name: 'item.webp', url: `${imageOrigin}/items/test/${randomUUID()}.webp` }
    await repository.replace('items', '880001', { images: [itemImage], expected: [], reason: '검증 이미지 등록' }, admin.id)
    assert.equal((await client.masterItemImage.findFirstOrThrow({ where: { masterItemId: '880001' } })).url, itemImage.url)
    const assetImages = Array.from({ length: 8 }, (_, index) => ({ id: randomUUID(), name: `asset-${index}.webp`, url: `${imageOrigin}/assets/test/${randomUUID()}.webp` }))
    const before = await client.customerChange.count()
    await repository.replace('assets', '260929-0001', { images: assetImages, expected: [], reason: '검증 자산 사진 등록' }, admin.id)
    const saved = await client.assetImage.findMany({ where: { assetId: '260929-0001' }, orderBy: { sortOrder: 'asc' } })
    assert.deepEqual(saved.map(({ id, name, url }) => ({ id, name, url })), assetImages)
    assert.equal(await client.customerChange.count(), before + 1)
    const data = await createAdminDataRepository(client).load(adminDataQuery.parse({ scope: 'assets', id: '260929-0001' }))
    assert.equal(data.assets[0]?.images.length, 8)
    assert.ok(Array.isArray(data.assets[0]?.history.at(-1)?.changes))
    const detail = await createAssetRepository(client).detail!('LEGACY-ASSET-OWNER', '260929-0001')
    assert.equal(detail?.images.length, 8)
    await assert.rejects(repository.replace('assets', '260929-0001', { images: [], expected: [], reason: '충돌 검증' }, admin.id), /변경되었습니다/)
    assert.equal(await client.customerChange.count(), before + 1)
    await assert.rejects(repository.replace('assets', '260929-0001', { images: [], expected: assetImages, reason: '원자성 검증' }, 'missing-actor'))
    assert.equal(await client.assetImage.count({ where: { assetId: '260929-0001' } }), 8)
    const results = await Promise.allSettled([
      repository.replace('assets', '260929-0001', { images: assetImages.slice(0, 1), expected: assetImages, reason: '동시 저장 A' }, admin.id),
      repository.replace('assets', '260929-0001', { images: assetImages.slice(0, 2), expected: assetImages, reason: '동시 저장 B' }, admin.id),
    ])
    assert.equal(results.filter((result) => result.status === 'fulfilled').length, 1)
    assert.equal(await client.customerChange.count(), before + 2)
  })
  await context.test('existing item edits persist metadata and images and preserve linked assets on code changes', async () => {
    const repository = createAdminDataRepository(client)
    const before = (await repository.load(adminDataQuery.parse({ scope: 'items', id: '880001' }))).items[0]!
    const input = { ...before, id: '880002', name: '수정된 품목', category: before.category || null, specification: '수정 규격', brand: 'MRS', unit: 'EA' as const, inboundPrice: 0, outboundPrice: 1500, standardPrice: null, enabled: false, note: '저장 검증' }
    const auditBefore = await client.customerChange.count({ where: { action: 'item.update' } })
    await repository.updateItem('880001', input, admin.id)
    const saved = (await repository.load(adminDataQuery.parse({ scope: 'items', id: '880002' }))).items[0]!
    assert.equal(saved.name, input.name)
    assert.equal(saved.specification, input.specification)
    assert.equal(saved.brand, input.brand)
    assert.equal(saved.inboundPrice, 0)
    assert.equal(saved.outboundPrice, 1500)
    assert.equal(saved.standardPrice, null)
    assert.equal(saved.enabled, false)
    assert.equal(saved.note, input.note)
    assert.deepEqual(saved.images, before.images)
    assert.equal((await client.asset.findUniqueOrThrow({ where: { id: '260929-0001' } })).itemId, '880002')
    assert.equal(await client.masterItem.count({ where: { id: '880001' } }), 0)
    await assert.rejects(repository.updateItem('880002', { ...input, unit: 'M' }, admin.id), /기준 단위/)
    await assert.rejects(repository.updateItem('880002', { ...input, id: '990001' }, admin.id), /상태/)
    await assert.rejects(repository.updateItem('880002', { ...input, name: '롤백 검증' }, 'missing-actor'))
    assert.equal((await client.masterItem.findUniqueOrThrow({ where: { id: '880002' } })).name, input.name)
    assert.equal(await client.customerChange.count({ where: { action: 'item.update' } }), auditBefore + 1)
    await assert.rejects(repository.updateItem('880002', { ...input, images: [{ id: randomUUID(), name: 'unsafe.jpg', url: 'https://example.com/unsafe.jpg' }] }, admin.id), /S3/)
    await assert.rejects(repository.updateItem('000000', input, admin.id), /찾을 수 없습니다/)
  })
  await context.test('concurrent edits only commit one version and one audit event', async () => {
    const current = await customers.detail(company.id)
    const before = await client.customerChange.count()
    const results = await Promise.allSettled([
      customers.update(company.id, { ...fields, name: 'First edit' }, { version: current.version, reason: 'First' }, admin.id),
      customers.update(company.id, { ...fields, name: 'Second edit' }, { version: current.version, reason: 'Second' }, admin.id),
    ])
    assert.equal(results.filter((result) => result.status === 'fulfilled').length, 1)
    assert.equal(await client.customerChange.count(), before + 1)
  })
})